default:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_USER', 'postgres') }}"
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD', 'postgrespassword') }}"
      port: "{{ env_var('DBT_PORT', '5432') | int }}"
      dbname: "{{ env_var('DBT_DBNAME', 'ecom_production') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'analytics') }}"
      threads: 4
  target: dev
